name: C Build Test

on:
  push:
    branches: [windows]
  pull_request:
    branches: [windows]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Configure CMake
      run: cmake -B build

    - name: Build project
      run: cmake --build build

    - name: Convert to assembly
      run: cmake --build build --target asm

    - name: Run Basic Tests
      run: |
        # This checks if the executable was actually created
        if [ -f ./build/Terminal ]; then
          echo "Build successful!"
        else
          echo "Executable not found!"
          exit 1
        fi
